spring.application.name=avaliacao20260520

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_aula20260520
spring.datasource.username=root
spring.datasource.password=
